# -----------------------------------------------------------------------------
#
# Plot microsporidia - yeast protein length histograms
#
# Jason Jiang - Created: 2022/01/30
#               Last edited: 2022/03/14
#
# Reinke Lab - Microsporidia Orthologs Project
#
# Goal: Create histograms of microsporidia protein lengths vs their yeast
#       orthologs, for each individual microosporidia species and all
#       microsporidia together.
#
# Thanks to Brandon Murareanu for this RScript layout
#
#
# -----------------------------------------------------------------------------

suppressMessages(library(tidyverse))

################################################################################

main <- function() {
  # ----------------------------------------------------------------------------
  # $1 = directory with csvs of Orthofinder single-copy orthogroups for each
  #      microsporidia species and yeast
  #
  # $2 = filepath to text file of all essential genes in yeast, named with their
  #      Uniprot protein names
  #
  # $3 = filepath to output directory
  # ----------------------------------------------------------------------------
  args <- commandArgs(trailingOnly = T)
  sco_data_dir <- args[1]
  essential_genes <- readLines(args[2])
  out <- args[3]
  
  plot_histograms(sco_data_dir, essential_genes, out)
}

################################################################################

# Helper functions

plot_histograms <- function(sco_data_dir, essential_genes, out) {
  # ----------------------------------------------------------------------------
  # Plot histograms of ortholog pair lengths for each microsporidia species
  # and yeast.
  #
  # Arguments:
  #   sco_data_dir: directory with information about all single-copy orthogroups
  #                 between each microsporidia species and yeast, generated by
  #                 'find_orthogroups' Snakefile.
  #
  #   essential_genes: list of essential yeast genes, with Uniprot gene names
  #
  #   out: filepath to directory which to save histogram plots in
  # ----------------------------------------------------------------------------
  # return list of species + names
  sco_files <- list.files(sco_data_dir, pattern = '*.csv', full.names = T)
  
   # draw histogram for each individual species
  dir.create(str_c(out, '/by_species'))  # directory for single species plots
  merged_sco_dfs <- list()
  
  for (file in sco_files) {
    sp_name <- str_extract(file, "[:upper:]_[:lower:]{2,4}\\.?")
    
    sp_sco_df <- format_sco_df(read_csv(file, show_col_types = F), sp_name) %>%
      mutate(essential = yeast %in% essential_genes,
             microsp_yeast_ratio = microsp_len / yeast_len)
    
    merged_sco_dfs[[sp_name]] <- sp_sco_df
    
    # draw histogram for single species' proteins
    plot_length_histogram(sp_sco_df, sp_name, str_c(out, '/by_species'))
  }
  
  # draw histogram for all species together
  merged_sco_dfs <- bind_rows(merged_sco_dfs)
  plot_length_histogram(merged_sco_dfs, 'All species', out)
  
  # save a dataframe with all microsporidia-yeast single copy orthogroups and
  # relative lengths of each microsporidia ortholog to its yeast ortholog
  write_csv(merged_sco_dfs, str_c(out, '/merged_SCOs.csv'))
}


format_sco_df <- function(sco_df, sp_name) {
  # ----------------------------------------------------------------------------
  # Rename and rearrange columns in dataframes of orthofinder sco data, so all
  # dataframes for all microsporidia species have the same format.
  #
  # sco_df: dataframe of orthogroups + protein lengths for a microsporidia
  #         species and yeast
  #
  # sp_name: name of the microsporidia species
  # ----------------------------------------------------------------------------
  sco_df <- sco_df %>%
    rename(microsp = !!sp_name,
           microsp_len = !!str_c(sp_name, '_len'),
           orthogroup = Orthogroup,
           yeast = S_cere,
           yeast_len = S_cere_len) %>%
    mutate(name = sp_name) %>%
    select(orthogroup, name, microsp, yeast, microsp_len, yeast_len)
  
  return(sco_df)
}


plot_length_histogram <- function(sco_df, label, out) {
  # ----------------------------------------------------------------------------
  # Creates and saves a histogram of relative lengths of microsporidia orthologs
  # to their yeast orthologs.
  #
  # Arguments:
  #   sco_df: dataframe with info on single-copy orthogroup sequence lengths for
  #           a microsporidia species and yeast
  #
  #   label: name of the microsporidia species to title the histogram with
  #
  #   out: filepath + filename to save histogram under
  # ----------------------------------------------------------------------------
  # Add function for grouping orthologs by length
  get_length_category <- function(ratio) {
    if (ratio < 0.3) {
      return('<30%')
    } else if (0.3 <= ratio & ratio <= 0.6) {
      return('30% - 60%')
    } else if (0.6 <= ratio & ratio <= 0.9) {
      return('60% - 90%')
    } else {
      return('>90%')
    }
  }
  get_length_category <- Vectorize(get_length_category)
  
  # add column for length ratio category
  sco_df <- sco_df %>%
    mutate(category = get_length_category(microsp_yeast_ratio))
  
  # convert length ratio categories to ordered factors for plotting
  sco_df$category <- factor(sco_df$category,
                            levels = c('<30%', '30% - 60%', '60% - 90%', '>90%'))
  
  hist_plot <- sco_df %>%
    ggplot(aes(x = category, fill = essential)) +
    geom_bar(position = 'dodge', color = 'black') +
    # add labels for counts on top of bars
    geom_text(aes(label = ..count..), stat = 'count',
              position = position_dodge(0.9), vjust=-0.2) +
    scale_fill_manual(values = c('white', 'black')) +
    labs(x = 'Relative length of microsporidia ortholog to yeast ortholog',
         title = label) +
    theme(title = element_text(size = 18, color = 'black'),
          axis.title = element_text(size = 18, color = 'black'),
          axis.text = element_text(size = 14, color = 'black')) +
    theme_bw()
  
  ggsave(filename = str_c(label, '.tiff'),
         plot = hist_plot,
         path = str_c(out, '/'),
         height = 4.25,
         width = 5.25,
         units = 'in',
         dpi = 600)
}

################################################################################

main()