# -----------------------------------------------------------------------------
#
# Get lost microsporidia domains for PCA
#
# Jason Jiang - Created: 2022/01/26
#               Last edited: 2022/01/26
#
# Reinke Lab - Microsporidia Orthologs Project
#
# Goal: From a dataframe of domain architecture alignments for all microsporidia
#       species and their yeast orthologs, create a list of all Pfam clans
#       lost in microsporidia orthologs, with their loss rates in each species.
#
# Thanks to Brandon Murareanu for this RScript layout
#
#
# -----------------------------------------------------------------------------

suppressMessages(library(tidyverse))

################################################################################

main <- function() {
  # ----------------------------------------------------------------------------
  # $1 = filepath to csv file of combined domain architecture alignments
  # $2 = filepath to rds file with hashmap mapping pfam domains to their clans
  # $3 = filepath to rds file mapping microsporidia species to their clades
  # $4 = full file path for the file we want to save our lost domain list to
  # ----------------------------------------------------------------------------
  args <- commandArgs(trailingOnly = T)
  merged_aligned_DA <- read_csv(args[1], show_col_types = F)
  clan_hash <- readRDS(args[2])
  clade_hash <- readRDS(args[3])
  out <- args[4]
  
  lost_clans_count <- get_lost_clans(merged_aligned_DA, clan_hash, clade_hash)
  write_csv(lost_clans_count[[1]], out)
  write_csv(lost_clans_count[[2]], str_replace(out, '.csv', '_normalized.csv'))
}

################################################################################

# Helper functions

get_lost_clans <- function(merged_aligned_DA, clan_hash, clade_hash) {
  # ----------------------------------------------------------------------------
  # Returns a dataframe of the normalized frequency in which Pfam clans are lost
  # in each microsporidia species.
  #
  # merged_aligned_DA: dataframe of aligned domain architectures for all
  # microsporidia species, generated by 'merge_domain_arch_dataframes.R'
  #
  # clan_hash: hashtable mapping Pfam domains back to their clans
  # ----------------------------------------------------------------------------
  lost_clans_list <- merged_aligned_DA %>%
    # filter to microsporidia orthologs with lost domains
    filter(!is.na(lost_doms)) %>%
    select(species, lost_doms) %>%
    # ensure each domain is lost at most once in each microsporidia ortholog
    mutate(lost_doms = get_unique_doms(lost_doms)) %>%
    separate_rows(lost_doms, sep = ', ') %>%
    rowwise() %>%
    # convert each lost domain back to its Pfam clan, and add the clade
    # each microsporidia species belongs to
    mutate(lost_clans = get_clan(lost_doms, clan_hash),
           clade = clade_hash[[species]]) %>%
    select(species, clade, lost_clans, -lost_doms) %>%
    group_by(species, clade, lost_clans) %>%
    summarise(n = n())
  
  # normalize clan loss rates by subtracting mean rate and dividing by
  # standard deviation
  return(normalize_clan_counts(lost_clans_list))
}


get_unique_doms <- function(lost_doms) {
  # ----------------------------------------------------------------------------
  # Returns a comma separated string of only the unique domains in lost_doms.
  # ----------------------------------------------------------------------------
  return(str_c(unique(str_split(lost_doms, ', ')[[1]]), collapse = ', '))
}
get_unique_doms <- Vectorize(get_unique_doms)


get_clan <- function(dom, clan_hash) {
  # ----------------------------------------------------------------------------
  # Returns the corresponding Pfam clan for a particular Pfam domain.
  # If no clan is assigned for the domain, just return the domain.
  #
  # dom: Name of Pfam domain
  # clan_hash: hashtable mapping Pfam domains to their clans
  # ----------------------------------------------------------------------------
  clan <- clan_hash[[dom]]
  return(ifelse(!is.na(clan), clan, dom))
}


fill_missing_clans <- function(lost_clans_list) {
  # ----------------------------------------------------------------------------
  # For each species, add rows of zero for missing clans
  # ----------------------------------------------------------------------------
  # get all unique clans that have been lost across microsporidia
  clans <- unique(lost_clans_list$lost_clans)
  
  # separate lost_clans_list dataframe into separate dataframes for each species
  sp_lost_clans <- lost_clans_list %>%
    group_by(species) %>%
    group_split()
  
  for (i in 1 : length(sp_lost_clans)) {
    # get clans that weren't lost in this microsporidia species
    missing_clans <- setdiff(clans, sp_lost_clans[[i]]$lost_clans)
    
    # create dataframe of all missing domains for this species, with a count
    # of zero
    missing_clans <- data.frame(
      species = unique(sp_lost_clans[[i]]$species),
      clade = unique(sp_lost_clans[[i]]$clade),
      lost_clans = missing_clans,
      n = 0
    )
    
    # add these missing domains to the original species dataframe
    sp_lost_clans[[i]] <- rbind(sp_lost_clans[[i]], missing_clans)
  }
  
  # join all the split dataframes back together, now with rows added for missing
  # clans in each species
  return(bind_rows(sp_lost_clans))
}


normalize_clan_counts <- function(lost_clans_list) {
  lost_clans_list <- fill_missing_clans(lost_clans_list)
  
  n_normalized <- lost_clans_list %>%
    group_by(lost_clans) %>%
    mutate(n_normalized = (n - mean(n)) / sd(n)) %>%
    select(-n) %>%
    spread(lost_clans, n_normalized)
  
  lost_clans_list <- spread(lost_clans_list, lost_clans, n)
  
  # return dataframes with both normalized and unnormalized n values
  return(list(lost_clans_list, n_normalized))
}

################################################################################

main()