# -----------------------------------------------------------------------------
#
# Plot DA change rates
#
# Jason Jiang - Created: 2022/01/25
#               Last edited: 2022/03/29
#
# Reinke Lab - Microsporidia Orthologs Project
#
# Goal: For each microsporidia species, plot the frequencies of domain loss,
#       gain and swap with their yeast orthologs.
#
# Thanks to Brandon Murareanu for this RScript layout
#
#
# ------------------------------------------------------------------------------

suppressMessages(library(tidyverse))

################################################################################

main <- function() {
  # ----------------------------------------------------------------------------
  # $1 = merged DA csv file
  # $2 = output directory
  # ----------------------------------------------------------------------------
  args <- commandArgs(trailingOnly = T)
  merged_DA_df <- read_csv(args[1], show_col_types = F)
  output_dir <- args[2]
  
  microsp_names <- unique(merged_DA_df$species)
  
  # draw overall plot of DA change frequencies for all microsporidia species
  draw_DA_change_plot(merged_DA_df, output_dir, 'All_species')
  
  # draw plots for individual microsporidia species
  for (name in microsp_names) {
    sp_df <- filter(merged_DA_df, species == name)
    draw_DA_change_plot(sp_df, output_dir, name)
  }
}

################################################################################

# Helper functions

draw_DA_change_plot <- function(sp_df, output_dir, plot_name) {
  # ----------------------------------------------------------------------------
  # Draws a plot of rates of domain loss, gain and swap for each species in
  # merged_DA_df, saving the plots as pngs into the specified output_dir.
  #
  # Arguments:
  # merged_DA_df: dataframe of merged domain architectures from all microsporidia
  #               species, generated by merge_domain_arch_dataframes.R
  #
  # output_dir: filepath to output directory for saving the plots in
  #
  # plot_name: what to title the plot (microsporidia species name, etc)
  # ----------------------------------------------------------------------------
  # get all microsporidia species names
  sp_df <- sp_df %>%
    # add columns indicating whether a particular microsporidia ortholog has
    # undergone domain gain, swap and/or loss
    # use these columns for plotting later
    mutate(lost = as.integer(!is.na(lost_doms)),
           gain = as.integer(!is.na(gained_doms)),
           swap = as.integer(!is.na(swapped_doms))) %>%
    # count number of essential and non-essential ortholog pairs with
    # domain loss, gain and swap
    # each ortholog pair can undergo multiple changes
    group_by(essential) %>%
    summarise(n_lost = sum(lost), n_gain = sum(gain), n_swap = sum(swap))
  
  # reshape sp_df
  # TODO - rewrite this sloppy crap
  essential <- filter(sp_df, essential)
  non_essential <- filter(sp_df, !essential)
  
  num_essential <- essential$n_gain + essential$n_lost + essential$n_swap
  num_non_essential <-
    non_essential$n_gain + non_essential$n_lost + non_essential$n_swap
  
  ess <- c(F, T, F, T, F, T)
  labs <- c('Loss', 'Loss', 'Gain', 'Gain', 'Swap', 'Swap')
  vals <- c(sp_df$n_lost, sp_df$n_gain, sp_df$n_swap)
  totals <- rep(c(num_non_essential, num_essential), 3)
  
  sp_df <- data.frame(Essential = ess, DA_change = labs, n = vals, N = totals) %>%
    mutate(group_prop = n / N)
  
  # draw plot of number of occurences of domain gain, loss and swap, and save
  # the plot as a png
  sp_plot <- ggplot(data = sp_df, aes(x = DA_change, y = group_prop, fill = Essential)) +
    geom_bar(stat = 'identity', position = 'dodge', color = 'black') +
    scale_fill_manual(values = c('black', 'white')) +
    labs(y = '% of ortholog pairs',
         title = plot_name) +
    theme_bw() +
    theme(title = element_text(size = 18, color = 'black'),
          axis.text = element_text(size = 18, color = "black"),
          axis.title = element_text(size = 18),
          axis.title.x = element_blank())
  
  ggsave(plot = sp_plot, filename = str_c(plot_name, '.tiff'),
         path = output_dir, dpi = 600, width = 4.8, height = 4.8, unit = 'in')
}

################################################################################

main()  # run the script