# -----------------------------------------------------------------------------
#
# dcGOR domain functional enrichment
#
# Jason Jiang - Created: 2022/03/23
#               Last edited: 2022/03/23
#
# Reinke Lab - Microsporidia Orthologs Project
#
# Goal: Use dcGOR and the pfam2go collection of Pfam domain family GO
# annotations, to find enriched biological process / molecular function
# GO terms in the set of domains lost by Microsporidia orthologs to yeast
#
# Thanks to Brandon Murareanu for this RScript layout
#
#
# -----------------------------------------------------------------------------

suppressMessages(library(dcGOR))
suppressMessages(library(tidyverse))

################################################################################

main <- function() {
  # ---------------------------------------------------------------------------
  # Command line arguments:
  #   $1 = directory with all files for dcGOR to use, generated by
  #        prep_dcGOR_files.R
  #   #2 = filepath to file with aligned microsporidia - yeast domain archs
  #   $3 = unformatted Pfam data
  #   $4 = formatted pfam2go data
  #   $5 = directory for dcGOR output files to go into
  # ---------------------------------------------------------------------------
  # Parse in command line arguments
  args <- commandArgs(trailingOnly = T)
  input_dir <- args[1]
  aligned_DA <- read_csv(args[2], show_col_types = F)
  pfam_data <- read_tsv(args[3], show_col_types = F)
  pfam2go <- read_csv(args[4], show_col_types = F)
  output_dir <- args[5]
  
  # Code for this section is based on https://supfam.org/dcGOR/demo-Customisation.html
  # tutorial from dcGOR on performing domain function enrichment analyses with
  # custom domain function annotations
  
  # First, create an object for all Pfam domains
  pfam_domains <- dcBuildInfoDataFrame(input.file = str_c(input_dir, '/pfam_formatted.tsv'),
                                       output.file = str_c(output_dir, '/pfam_domains.RData'))
  
  # Then, create objects for GOBP and GOMP GO annotations
  # Due to some errors in scanning in files by dcBuildOnto, I called
  # trace(dcBuildOnto, edit = T) and added 'fill = T' to line 16 of the source
  # code
  onto_bio <- dcBuildOnto(relations.file = str_c(input_dir, '/GO_bio_edges.tsv'),
                          nodes.file = str_c(input_dir, '/GO_bio_nodes.tsv'),
                          output.file = str_c(output_dir, '/onto_bio.RData'))
  
  onto_mol <- dcBuildOnto(relations.file = str_c(input_dir, '/GO_mol_edges.tsv'),
                          nodes.file = str_c(input_dir, '/GO_mol_nodes.tsv'),
                          output.file = str_c(output_dir, '/onto_mol.RData'))
  
  # Finally, create objects for associations between Pfam domain IDs and GOBP /
  # GOMF annotations
  bio_annot <- dcBuildAnno(domain_info.file = str_c(input_dir, '/pfam_formatted.tsv'),
                           term_info.file = str_c(input_dir, '/GO_bio_term_info.tsv'),
                           association.file = str_c(input_dir, '/pfam2go_bio.tsv'),
                           output.file = str_c(output_dir, '/bio_annot.RData'))
  
  mol_annot <- dcBuildAnno(domain_info.file = str_c(input_dir, '/pfam_formatted.tsv'),
                           term_info.file = str_c(input_dir, '/GO_mol_term_info.tsv'),
                           association.file = str_c(input_dir, '/pfam2go_mol.tsv'),
                           output.file = str_c(output_dir, '/mol_annot.RData'))
  
  # Get list of all lost domains
  lost_doms <- (filter(aligned_DA, !is.na(lost_doms)) %>%
    select(species, yeast, lost_doms) %>%
    separate_rows(lost_doms, sep = ', '))$lost_doms
  
  # map Pfam family names to Pfam IDs
  fam_to_id <- make_fam_to_id_hash(pfam_data)
  lost_doms <- unname(sapply(lost_doms, function(x) {fam_to_id[[x]]}))
  
  # get list of all unique pfam2go domains for background in enrichment
  pfam2go_bkrd <- unique(pfam2go$pfam_ID)
  
  # Do GO biological process and GO molecular function enrichment for our list
  # of lost microsporidia domains, with all pfam2go domains as the background
  GOBP_enrich <- dcEnrichment(lost_doms,
                              background = pfam2go_bkrd,
                              domain.RData = str_c(output_dir, '/pfam_domains.RData'),
                              ontology.RData = str_c(output_dir, '/onto_bio.RData'),
                              annotations.RData = str_c(output_dir, '/bio_annot.RData'))
  
  GOMF_enrich <- dcEnrichment(lost_doms,
                              background = pfam2go_bkrd,
                              domain.RData = str_c(output_dir, '/pfam_domains.RData'),
                              ontology.RData = str_c(output_dir, '/onto_mol.RData'),
                              annotations.RData = str_c(output_dir, '/mol_annot.RData'))
  
  # Save dcGOR outputs as a table
  write(GOBP_enrich, str_c(output_dir, 'dcGOR_GOBP_enriched_slim.txt'))
  write(GOMF_enrich, str_c(output_dir, 'dcGOR_GOMF_enriched_slim.txt'))
}

################################################################################

### Helper functions

make_fam_to_id_hash <- function(pfam_data) {
  fam_to_id <- new.env()
  for (i in 1 : nrow(pfam_data)) {
    fam_to_id[[pfam_data[['Family_ID']][i]]] <- pfam_data[['Pfam_ID']][i]
  }
  
  return(fam_to_id)
}