# -----------------------------------------------------------------------------
#
# Prepare files for dcGOR
#
# Jason Jiang - Created: 2022/03/23
#               Last edited: 2022/03/23
#
# Reinke Lab - Microsporidia Orthologs Project
#
# Goal: Prepare custom files needed to use Pfam2GO Pfam domain GO annotations
#       for dcGOR.
#
#       Format of required files taken from
#       https://supfam.org/dcGOR/demo-Customisation.html
#
#
# Thanks to Brandon Murareanu for this RScript layout
#
#
# -----------------------------------------------------------------------------

suppressMessages(library(tidyverse))
suppressMessages(library(ontologyIndex))  # For reading .obo gene ontology files

################################################################################

### Global variables

BP_GO_ID <- 'GO:0008150'  # parent GO term for all biological process terms
MF_GO_ID <- 'GO:0003674'  # parent GO term for all molecular function terms

################################################################################

main <- function() {
  # ---------------------------------------------------------------------------
  # Command line arguments:
  #   $1 = filepath to .obo file of GO terms
  #   $2 = filepath to tsv of Pfam domain data
  #   $3 = filepath to formatted pfam2go data, generated by parse_pfam2go.R
  #   $4 = filepath to directory to save all files for dcGOR in
  # ---------------------------------------------------------------------------
  # Parse in command line arguments
  args <- commandArgs(trailingOnly = T)
  GO_data <- as.data.frame(get_ontology(args[1], propagate_relationships = "is_a",
                          extract_tags = "minimal"))
  pfam_data <- read_tsv(args[2], show_col_types = F)
  pfam2go <- read_csv(args[3], show_col_types = F)
  out <- args[4]
  
  # Separate GO_data into biological process terms only, and molecular function
  # terms only
  GO_bio <- GO_data %>%
    filter(str_detect(ancestors, BP_GO_ID))
  
  GO_mol <- GO_data %>%
    filter(str_detect(ancestors, MF_GO_ID))
  
  # Create the relationship tables for edges between GO terms
  GO_bio_edges <- make_edges_table(GO_bio, BP_GO_ID)
  GO_mol_edges <- make_edges_table(GO_mol, MF_GO_ID)
  
  # Create nodes tables
  GO_bio_nodes <- make_nodes_table(GO_bio, 'biological_process')
  GO_mol_nodes <- make_nodes_table(GO_mol, 'molecular_function')
  
  # Create term info tables for dcBuildAnno function in dcGOR
  GO_bio_term_info <- make_term_info_table(GO_bio_nodes)
  GO_mol_term_info <- make_term_info_table(GO_mol_nodes)
  
  # Format list of all Pfam domains for dcGOR
  # See http://dcgor.r-forge.r-project.org/data/InterPro/InterPro.txt for
  # example of file needed
  pfam_data <- format_pfam_data(pfam_data)
  
  # Create subsets of pfam2go data for only biological process and molecular
  # function terms (association files used by dcBuildOnto)
  pfam2go_bio <- pfam2go %>%
    filter(GO_ID %in% GO_bio$id) %>%
    select(pfam_ID, GO_ID) %>%
    rename('pfam' = pfam_ID, 'term' = GO_ID)
  
  pfam2go_mol <- pfam2go %>%
    filter(GO_ID %in% GO_mol$id) %>%
    select(pfam_ID, GO_ID) %>%
    rename('pfam' = pfam_ID, 'term' = GO_ID)
  
  # Finally, write all the generated data for dcGOR as tsv files
  write_tsv(GO_bio_edges, str_c(out, '/GO_bio_edges.tsv'))
  write_tsv(GO_mol_edges, str_c(out, '/GO_mol_edges.tsv'))
  
  write_tsv(GO_bio_nodes, str_c(out, '/GO_bio_nodes.tsv'))
  write_tsv(GO_mol_nodes, str_c(out, '/GO_mol_nodes.tsv'))
  
  write_tsv(GO_bio_term_info, str_c(out, '/GO_bio_term_info.tsv'))
  write_tsv(GO_mol_term_info, str_c(out, '/GO_mol_term_info.tsv'))
  
  write_tsv(pfam_data, str_c(out, '/pfam_formatted.tsv'))
  write_tsv(pfam2go_bio, str_c(out, '/pfam2go_bio.tsv'))
  write_tsv(pfam2go_mol, str_c(out, '/pfam2go_mol.tsv'))
}

################################################################################

### Helper functions

make_edges_table <- function(GO_data, parent_id) {
  # ---------------------------------------------------------------------------
  # Creates edges table connecting GO terms to each other, required by dcGOR
  #
  # See http://dcgor.r-forge.r-project.org/data/onto/igraph_GOBP_edges.txt for
  # example input file
  #
  # Arguments:
  #   GO_data: dataframe of GO data, parsed in by get_ontology
  #   parent_id: GO ID of parent term (ie: biological process, molecular function)
  # ---------------------------------------------------------------------------
  edges <- GO_data %>%
    select(parents, id) %>%
    # Exclude entry for biological process / molecular function itself
    filter(id != parent_id) %>%
    rename('to' = id, 'from' = parents) %>%
    separate_rows(from, sep = '; ') %>%
    filter(!is.na(from) & !is.na(to)) %>%
    distinct(from, to)
  
  return(edges)
}


make_nodes_table <- function(GO_data, term_namespace) {
  # ---------------------------------------------------------------------------
  # Creates nodes table for GO terms, required by dcGOR
  #
  # See http://dcgor.r-forge.r-project.org/data/onto/igraph_GOMF_nodes.txt for
  # example input file
  # ---------------------------------------------------------------------------
  nodes <- GO_data %>%
    rowwise() %>%
    select(id, name, ancestors) %>%
    rename('Name' = name) %>%
    mutate(name = id, term_id = id, term_name = Name,
           term_namespace = term_namespace,
           term_distance = length(str_split(ancestors, '; ')[[1]]) - 1) %>%
    select(name, term_id, term_name, term_namespace, term_distance) %>%
    arrange(term_distance)
  
  return(nodes)
}


make_term_info_table <- function(GO_data) {
  # ---------------------------------------------------------------------------
  # Blah
  # ---------------------------------------------------------------------------
  term_info <- GO_data %>%
    rename('ID' = term_id, 'Name' = term_name, 'Namespace' = term_namespace,
           'Distance' = term_distance) %>%
    select(ID, Name, Namespace, Distance)
  
  return(term_info)
}


format_pfam_data <- function(pfam_data) {
  # ---------------------------------------------------------------------------
  # Blah
  # ---------------------------------------------------------------------------
  pfam_data <- pfam_data %>%
    rename('id' = Pfam_ID, 'description' = Family_name) %>%
    mutate(level = 'Pfam') %>%
    select(id, level, description)
  
  return(pfam_data)
}

################################################################################

main()